# === BUILD STAGE TEMPLATE BELOW ===
# Do not manually edit below this line - build stages are managed by turbo/generators

FROM base AS APP_NAME-build
COPY . /usr/src/app
WORKDIR /usr/src/app
RUN --mount=type=cache,id=pnpm,target=/pnpm/store \
  pnpm install --filter "APP_NAME..." --frozen-lockfile --ignore-scripts
RUN pnpm --filter "APP_NAME" run build
RUN pnpm deploy --filter="APP_NAME" --prod --ignore-scripts "/prod/APP_NAME"
